/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp4project;

/**
 *
 * @author maxen
 */
public class JPanelScore extends javax.swing.JPanel {

    /**
     * Creates new form JPanelScore
     */
    public JPanelScore() {
        initComponents();
    }
    
    public void setScore(int score){
        labelScore.setText("Score : " + score);
    }
    
    public void setNbQuestions(int nbQ){
        labelNbQuestions.setText("Nombre de questions : " + nbQ);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelScore = new javax.swing.JLabel();
        labelNbQuestions = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        labelScore.setText("Score : ?");
        add(labelScore, new java.awt.GridBagConstraints());

        labelNbQuestions.setText("Nombre de questions : ?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        add(labelNbQuestions, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelNbQuestions;
    private javax.swing.JLabel labelScore;
    // End of variables declaration//GEN-END:variables
}
