/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package packVue;

import packControleur.ControleurModif;
import packModele.Etudiant;

/**
 *
 * @author maxen
 */
public class VueModif extends javax.swing.JDialog {

    private VueListe vl;
    private Etudiant etuModif;

    public VueModif(java.awt.Frame parent, boolean modal, VueListe vl) {
        super(parent, modal);
        
        this.vl = vl;
        

        for (Etudiant e : vl.getPromo().getListEtudiants()) {
            if (vl.getListe().getSelectedValue().toString().equals(e.toString())) {
                etuModif = e;
                break;
            }
        }
        
        this.setTitle("Modifierl'étudiant " + etuModif.getNumero());
        
        initComponents();
    }

    public Etudiant getEtuModif() {
        return etuModif;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelNum = new javax.swing.JLabel();
        labelNom = new javax.swing.JLabel();
        labelPrenom = new javax.swing.JLabel();
        labelBac = new javax.swing.JLabel();
        labelDpt = new javax.swing.JLabel();
        txtFieldNum = new javax.swing.JTextField();
        txtFieldNom = new javax.swing.JTextField();
        txtFieldPrenom = new javax.swing.JTextField();
        boxBac = new javax.swing.JComboBox<>();
        boxDpt = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        labelNum.setText("Numéro :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(labelNum, gridBagConstraints);

        labelNom.setText("Nom : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(labelNom, gridBagConstraints);

        labelPrenom.setText("Prénom :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(labelPrenom, gridBagConstraints);

        labelBac.setText("BAC : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(labelBac, gridBagConstraints);

        labelDpt.setText("Département :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(labelDpt, gridBagConstraints);

        txtFieldNum.setMinimumSize(new java.awt.Dimension(200, 22));
        txtFieldNum.setPreferredSize(new java.awt.Dimension(200, 22));
        getContentPane().add(txtFieldNum, new java.awt.GridBagConstraints());
        txtFieldNum.setText(etuModif.getNumero());

        txtFieldNom.setMinimumSize(new java.awt.Dimension(200, 22));
        txtFieldNom.setPreferredSize(new java.awt.Dimension(200, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        getContentPane().add(txtFieldNom, gridBagConstraints);
        txtFieldNom.setText(etuModif.getNom());

        txtFieldPrenom.setPreferredSize(new java.awt.Dimension(200, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        getContentPane().add(txtFieldPrenom, gridBagConstraints);
        txtFieldPrenom.setText(etuModif.getPrenom());

        boxBac.addItem("S");
        boxBac.addItem("STI");
        boxBac.addItem("ES");
        boxBac.addItem("STG");
        boxBac.addItem("Etranger");
        boxBac.addItem("Autre");
        boxBac.setPreferredSize(new java.awt.Dimension(200, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        getContentPane().add(boxBac, gridBagConstraints);
        boxBac.setSelectedItem(etuModif.getBac());

        for (int i = 1; i < 96; i++) {
            if (i != 20) {

                boxDpt.addItem("" + i);
            } else {
                boxDpt.addItem("2A");
                boxDpt.addItem("2B");
            }
        }
        for (int i = 971; i < 977; i++) {
            boxDpt.addItem("" + i);
        }
        boxDpt.addItem("Autre");
        boxDpt.setPreferredSize(new java.awt.Dimension(200, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        getContentPane().add(boxDpt, gridBagConstraints);
        boxDpt.setSelectedItem(etuModif.getDepartement());

        jButton1.setText("Modifier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jButton1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        
        String numero = txtFieldNum.getText();
        String nom = txtFieldNom.getText();
        String prenom = txtFieldPrenom.getText();
        String bac = boxBac.getSelectedItem().toString();
        String dpt = boxDpt.getSelectedItem().toString();
        
        Etudiant newEtu = new Etudiant(numero,nom,prenom,dpt,bac);
         ControleurModif controleurModif = new ControleurModif(vl,this,newEtu,etuModif);
        controleurModif.control();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxBac;
    private javax.swing.JComboBox<String> boxDpt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelBac;
    private javax.swing.JLabel labelDpt;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelNum;
    private javax.swing.JLabel labelPrenom;
    private javax.swing.JTextField txtFieldNom;
    private javax.swing.JTextField txtFieldNum;
    private javax.swing.JTextField txtFieldPrenom;
    // End of variables declaration//GEN-END:variables
}
